# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: ACT EQ PVP Zone Plugin

on:
  push:
    ignore-branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  
jobs:
  build:
    runs-on: windows-2019
    env:
      ACTFileName: 'ACTv3-setup.exe'
      ACTDownloadURI: 'https://advancedcombattracker.com/download.php?id=56'
      EQPVPZoneIndicatorLibraryPath: '.\EQPVPZoneIndicator\obj\Release\EQPVPZoneIndicator.dll'
    steps:
      - uses: actions/checkout@main
      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v1.1
      - name: Download ACTv3 file
        run: Invoke-WebRequest ${{env.ACTDownloadURI}} -OutFile ${{github.workspace}}\${{env.ACTFileName}}
      - name: Silent Install of ACTv3
        run: ${{github.workspace}}\${{env.ACTFileName}} /S
      - name: Setup Nuget
        uses: nuget/setup-nuget@v1
      - name: Restore nuget packages
        run: nuget restore EQPVPZoneIndicator.sln
      - name: Build solution
        run: msbuild -t:build -property:Configuration=Release /p:TargetFrameworkVersion=v4.8 EQPVPZoneIndicator.sln
      - name: Upload dll file to artifact repository
        uses: actions/upload-artifact@v4
        if: github.ref_type == 'tag'
        with:
          name: EQPVPZoneIndicator
          path: ${{ env.EQPVPZoneIndicatorLibraryPath }}
  release:
    needs: build
    runs-on: windows-2019
    permissions:
      contents: write
    if: github.ref_type == 'tag'
    steps:
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: false
          prerelease: false
      - uses: actions/download-artifact@v4
        with:
          name: EQPVPZoneIndicator
      - name: Upload Release Asset
        id: upload-release-asset 
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }} # This pulls from the CREATE RELEASE step above, referencing it's ID to get its outputs object, which include a `upload_url`. See this blog post for more info: https://jasonet.co/posts/new-features-of-github-actions/#passing-data-to-future-steps 
          asset_path: .\EQPVPZoneIndicator.dll
          asset_name: EQPVPZoneIndicator.dll
          asset_content_type: application/dll
